// Regenerates src/lib/client/icons-data.js from static/assets/icons/ (the main app's icon
// library) with only the icons the finder references, so the page never ships the whole set.
//   npm run build:icons
import { readFileSync, readdirSync, writeFileSync, statSync } from 'fs';
import { join, basename } from 'path';

const root = new URL('..', import.meta.url).pathname;

// Every component, action and module under src/ can name an icon.
function walk(dir) {
  return readdirSync(dir).flatMap(entry => {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) return walk(path);
    return /\.(svelte|js)$/.test(entry) && !entry.endsWith('icons-data.js') ? [path] : [];
  });
}
const sources = walk(join(root, 'src')).map(f => readFileSync(f, 'utf8')).join('\n');

const used = new Set();
for (const m of sources.matchAll(/icon\(\s*'([a-z0-9-]+)'/g)) used.add(m[1]);
for (const m of sources.matchAll(/\bicon:\s*'([a-z0-9-]+)'/g)) used.add(m[1]); // { icon: 'name' } maps
for (const m of sources.matchAll(/data-icon="([a-z0-9-]+)"/g)) used.add(m[1]);
for (const m of sources.matchAll(/<Icon\s[^>]*name="([a-z0-9-]+)"/g)) used.add(m[1]); // <Icon name="..." />

const available = new Set(readdirSync(join(root, 'static/assets/icons')).filter(f => f.endsWith('.svg')).map(f => basename(f, '.svg')));
const missing = [...used].filter(n => !available.has(n));
if (missing.length) {
  console.error(`Icons referenced but not in static/assets/icons/: ${missing.join(', ')}`);
  process.exit(1);
}

const entries = [...used].sort().map(name => {
  const svg = readFileSync(join(root, 'static/assets/icons', `${name}.svg`), 'utf8').replace(/\s+/g, ' ').replace(/> </g, '><').trim();
  return `  '${name}': ${JSON.stringify(svg)}`;
});

writeFileSync(join(root, 'src/lib/client/icons-data.js'), `// Generated by scripts/build-icons.mjs from static/assets/icons/. Do not edit by hand.\nexport const ICONS = {\n${entries.join(',\n')}\n};\n`);
console.log(`icons-data.js: ${entries.length} icons`);
