// Regenerates icons-data.js from assets/icons/ (the main app's icon library) with only the
// icons the finder references, so the page never ships the whole set.
//   npm run build:icons
import { readFileSync, readdirSync, writeFileSync } from 'fs';
import { join, basename } from 'path';

const root = new URL('..', import.meta.url).pathname;
const sources = ['index.html', 'app.js', 'picker.js'].map(f => readFileSync(join(root, f), 'utf8')).join('\n');

const used = new Set();
for (const m of sources.matchAll(/icon\(\s*'([a-z0-9-]+)'/g)) used.add(m[1]);
for (const m of sources.matchAll(/data-icon="([a-z0-9-]+)"/g)) used.add(m[1]);

const available = new Set(readdirSync(join(root, 'assets/icons')).filter(f => f.endsWith('.svg')).map(f => basename(f, '.svg')));
const missing = [...used].filter(n => !available.has(n));
if (missing.length) {
  console.error(`Icons referenced but not in assets/icons/: ${missing.join(', ')}`);
  process.exit(1);
}

const entries = [...used].sort().map(name => {
  const svg = readFileSync(join(root, 'assets/icons', `${name}.svg`), 'utf8').replace(/\s+/g, ' ').replace(/> </g, '><').trim();
  return `  '${name}': ${JSON.stringify(svg)}`;
});

writeFileSync(join(root, 'icons-data.js'), `// Generated by scripts/build-icons.mjs from assets/icons/. Do not edit by hand.\nexport const ICONS = {\n${entries.join(',\n')}\n};\n`);
console.log(`icons-data.js: ${entries.length} icons`);
